/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salary.management.system.dbms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.text.DateFormat;
import java.util.Date;


/**
 *
 * @author TARIF
 */
public class Allowance extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Allowance
     */
    public Allowance() {
        initComponents();
        conn=DBMS.db();
        Toolkit toolkit=getToolkit();
        //Dimension size=toolkit.getScreenSize();
        //setLocation(size.width-getWidth()/2,size.height/2-getHeight()/2);
        Update_table();
        l_empid.setText(String.valueOf(Emp.empId).toString());
        
    }
    public void Update_table()
    {
        try{
            String sql="SELECT * FROM `allowance`";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_allowance.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       /* finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e)
            {
                
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        l_empid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_overtime = new javax.swing.JTextField();
        txt_medical = new javax.swing.JTextField();
        txt_bonus = new javax.swing.JTextField();
        txt_other = new javax.swing.JTextField();
        txt_totalovertime = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_empid = new javax.swing.JTextField();
        txt_hour = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_allowance = new javax.swing.JTable();
        b_calculate = new java.awt.Button();
        b_clear = new java.awt.Button();
        b_save = new java.awt.Button();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 160, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Surname:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 240, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date Of Birth:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 280, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Basic Salary:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 320, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Overtime:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 160, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Medical:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 200, 160, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Bonus:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 240, 160, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Other");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 280, 160, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Total Overtime:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(790, 160, 180, 40);

        l_empid.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        l_empid.setForeground(new java.awt.Color(0, 255, 51));
        l_empid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_empid.setText("emp");
        jPanel1.add(l_empid);
        l_empid.setBounds(180, 740, 160, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Loged in As:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 740, 160, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Total Amount:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(810, 360, 160, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Rate Per Hour:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(800, 210, 170, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 255, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Department:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 360, 160, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Employee ID:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 50, 160, 40);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(270, 60, 650, 30);

        txt_firstname.setEditable(false);
        txt_firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_firstname);
        txt_firstname.setBounds(200, 210, 200, 30);

        txt_surname.setEditable(false);
        txt_surname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_surname);
        txt_surname.setBounds(200, 250, 200, 30);

        txt_dob.setEditable(false);
        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_dob);
        txt_dob.setBounds(200, 290, 200, 30);

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_salary);
        txt_salary.setBounds(200, 330, 200, 30);

        txt_department.setEditable(false);
        txt_department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_department);
        txt_department.setBounds(200, 370, 200, 30);

        txt_overtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_overtime.setText("0");
        jPanel1.add(txt_overtime);
        txt_overtime.setBounds(570, 170, 200, 30);

        txt_medical.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_medical.setText("0");
        jPanel1.add(txt_medical);
        txt_medical.setBounds(570, 210, 200, 30);

        txt_bonus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_bonus.setText("0");
        jPanel1.add(txt_bonus);
        txt_bonus.setBounds(570, 250, 200, 30);

        txt_other.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_other.setText("0");
        txt_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otherActionPerformed(evt);
            }
        });
        jPanel1.add(txt_other);
        txt_other.setBounds(570, 290, 200, 30);

        txt_totalovertime.setEditable(false);
        txt_totalovertime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_totalovertime.setText("0");
        jPanel1.add(txt_totalovertime);
        txt_totalovertime.setBounds(980, 170, 200, 30);

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_amount.setText("0.00");
        jPanel1.add(txt_amount);
        txt_amount.setBounds(980, 370, 200, 30);

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_empid);
        txt_empid.setBounds(200, 170, 200, 30);

        txt_hour.setEditable(false);
        txt_hour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_hour.setText("0");
        txt_hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hourActionPerformed(evt);
            }
        });
        jPanel1.add(txt_hour);
        txt_hour.setBounds(980, 220, 200, 30);

        table_allowance.setBackground(new java.awt.Color(204, 204, 204));
        table_allowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_allowance);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 450, 1030, 190);

        b_calculate.setBackground(new java.awt.Color(0, 153, 0));
        b_calculate.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        b_calculate.setForeground(new java.awt.Color(255, 255, 255));
        b_calculate.setLabel("Calculate");
        b_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calculateActionPerformed(evt);
            }
        });
        jPanel1.add(b_calculate);
        b_calculate.setBounds(1080, 530, 110, 34);

        b_clear.setBackground(new java.awt.Color(0, 153, 0));
        b_clear.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        b_clear.setForeground(new java.awt.Color(255, 255, 255));
        b_clear.setLabel("Clear");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });
        jPanel1.add(b_clear);
        b_clear.setBounds(1080, 590, 110, 34);

        b_save.setBackground(new java.awt.Color(0, 153, 0));
        b_save.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        b_save.setForeground(new java.awt.Color(255, 255, 255));
        b_save.setLabel("Save");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });
        jPanel1.add(b_save);
        b_save.setBounds(1080, 470, 110, 34);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salary/management/system/dbms/images/Allowance.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(-100, -30, 1470, 940);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otherActionPerformed

    private void txt_hourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hourActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
            int i=Integer.parseInt(txt_search.getText());
        String sql="SELECT * FROM `staff information` WHERE `id`="+i+"";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        rs.next();
           String add1=rs.getString("id");
           txt_empid.setText(add1);
           String add2=rs.getString("First_Name");
           txt_firstname.setText(add2);
           String add3=rs.getString("Surname");
           txt_surname.setText(add3);
           String add4=rs.getString("Date_Of_Birth");
           txt_dob.setText(add4);
           String add5=rs.getString("Salary");
           txt_salary.setText(add5);
           String add6=rs.getString("Department");
           txt_department.setText(add6);
        
        
        }catch(Exception e)
        {
          //  JOptionPane.showMessageDialog(null, e);
        }
        finally{
           try{ rs.close();
            pst.close();
           }catch(Exception e){
               
           }
        }
                
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Are You sure want to Save Allowance?","Save",JOptionPane.YES_NO_OPTION);
     if(x==0){
        try{
            int creat=Emp.empId;
            String salary=txt_salary.getText();
            String bonus=txt_bonus.getText();
            String medical=txt_medical.getText();
            String other=txt_other.getText();
            String overtime=txt_overtime.getText();
            String eid=txt_empid.getText();
            String rate=txt_hour.getText();
            String total=txt_amount.getText();
            String fname=txt_firstname.getText();
            String surname=txt_surname.getText();
            String sql="INSERT INTO `allowance`( `Overtime`, `Medical`, `Bonus`, `Other`, `Emp_id`, `Salary`, `Rate`, `Total_Allowance`, `First_Name`, `Surname`, `Created_by`) VALUES ('"+overtime+"','"+medical+"','"+bonus+"','"+other+"','"+eid+"','"+salary+"','"+rate+"','"+total+"','"+fname+"','"+surname+"','"+creat+"')";
         pst=conn.prepareStatement(sql);
         pst.execute();
         JOptionPane.showMessageDialog(null,"Allowance Added");
        Update_table();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
          
        
    }//GEN-LAST:event_b_saveActionPerformed
    }
    private void b_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calculateActionPerformed
        // TODO add your handling code here:
       try { int salary=Integer.parseInt(txt_salary.getText());
        int overtime=Integer.parseInt(txt_overtime.getText());
        
        double eight=8;
        double days=25;
        double dbop=0;
        double overrate=1.5;
        
        double total_overtime=overtime*overrate;
        String x=String.valueOf(total_overtime);
        txt_totalovertime.setText(x);
        
        dbop=salary/days/eight; 
        String s=String.valueOf(dbop);
        txt_hour.setText(s);
        
        int med=Integer.parseInt(txt_medical.getText());
        int bonus=Integer.parseInt(txt_bonus.getText());
        int other=Integer.parseInt(txt_other.getText());
        int f=med+bonus+other;
        double cal=total_overtime*dbop+f;
        String c=String.valueOf(cal);
        txt_amount.setText(c);
    }catch(Exception e){
        
    }
        
        
    }//GEN-LAST:event_b_calculateActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Are You sure want to Clear?","Clear",JOptionPane.YES_NO_OPTION);
     if(x==0){
        txt_empid.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_dob.setText("");
        txt_department.setText("");
        txt_salary.setText("");
        txt_overtime.setText("0");
        txt_medical.setText("0");
        txt_bonus.setText("0");
        txt_other.setText("0");
        txt_totalovertime.setText("0");
        txt_hour.setText("0");
        txt_amount.setText("0.00");
        l_empid.setText("");
    }//GEN-LAST:event_b_clearActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Allowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private java.awt.Button b_calculate;
    private java.awt.Button b_clear;
    private java.awt.Button b_save;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_empid;
    private javax.swing.JTable table_allowance;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bonus;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_hour;
    private javax.swing.JTextField txt_medical;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_overtime;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_totalovertime;
    // End of variables declaration//GEN-END:variables
}
