/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salary.management.system.dbms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author TARIF
 */
public class Deduction extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form Deduction
     */
    public Deduction() {
        initComponents();
        conn=DBMS.db();
        Toolkit toolkit=getToolkit();
        //Dimension size=toolkit.getScreenSize();
       // setLocation(size.width-getWidth()/2,size.height/2-getHeight()/2);
       
        l_empid.setText(String.valueOf(Emp.empId).toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        l_empid = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_hired = new javax.swing.JTextField();
        txt_title = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_totaldeduction = new javax.swing.JTextField();
        txt_salaryafter = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_empid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_percentage = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        r_amount = new javax.swing.JRadioButton();
        r_percentage = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        txt_reason = new javax.swing.JTextField();
        b_calculate = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();
        b_save = new javax.swing.JButton();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("Employee ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 140, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 190, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Surname:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 240, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date Of Birth:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 290, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Department:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 330, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Designation:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(550, 140, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 190, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Date Hired:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 240, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Job Title:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 290, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Basic Salary:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(550, 340, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Update Salary by:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 450, 220, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Total Deduction:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(760, 410, 190, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Salary After Deduction:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(670, 460, 280, 40);

        l_empid.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        l_empid.setForeground(new java.awt.Color(153, 153, 0));
        l_empid.setText("emp");
        jPanel1.add(l_empid);
        l_empid.setBounds(220, 700, 160, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Logged in As:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 700, 160, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 51));
        jLabel20.setText("Employee ID:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 50, 160, 30);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(240, 50, 710, 30);

        txt_fname.setEditable(false);
        txt_fname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_fname);
        txt_fname.setBounds(230, 190, 260, 31);

        txt_surname.setEditable(false);
        txt_surname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_surname);
        txt_surname.setBounds(230, 240, 260, 31);

        txt_dob.setEditable(false);
        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_dob);
        txt_dob.setBounds(230, 290, 260, 31);

        txt_department.setEditable(false);
        txt_department.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_department);
        txt_department.setBounds(230, 340, 260, 31);

        txt_designation.setEditable(false);
        txt_designation.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_designation);
        txt_designation.setBounds(720, 140, 260, 31);

        txt_status.setEditable(false);
        txt_status.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_status);
        txt_status.setBounds(720, 190, 260, 31);

        txt_hired.setEditable(false);
        txt_hired.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_hired);
        txt_hired.setBounds(720, 240, 260, 31);

        txt_title.setEditable(false);
        txt_title.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_title);
        txt_title.setBounds(720, 290, 260, 31);

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_salary);
        txt_salary.setBounds(720, 340, 260, 31);

        txt_totaldeduction.setEditable(false);
        txt_totaldeduction.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_totaldeduction.setText("0.00");
        jPanel1.add(txt_totaldeduction);
        txt_totaldeduction.setBounds(960, 410, 170, 31);

        txt_salaryafter.setEditable(false);
        txt_salaryafter.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_salaryafter.setText("0.00");
        txt_salaryafter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryafterActionPerformed(evt);
            }
        });
        jPanel1.add(txt_salaryafter);
        txt_salaryafter.setBounds(960, 470, 170, 31);

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_amount);
        txt_amount.setBounds(480, 530, 190, 30);

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_empid);
        txt_empid.setBounds(230, 140, 260, 31);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Reason:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(70, 590, 160, 40);

        txt_percentage.setEditable(false);
        txt_percentage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_percentage);
        txt_percentage.setBounds(250, 530, 100, 31);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Amount:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(360, 530, 110, 30);

        r_amount.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        r_amount.setForeground(new java.awt.Color(255, 204, 0));
        r_amount.setText("Amount");
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });
        jPanel1.add(r_amount);
        r_amount.setBounds(440, 450, 130, 33);

        r_percentage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        r_percentage.setForeground(new java.awt.Color(255, 204, 0));
        r_percentage.setText("Percentage(%)");
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });
        jPanel1.add(r_percentage);
        r_percentage.setBounds(240, 450, 190, 33);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Percentage:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(80, 530, 160, 30);

        txt_reason.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jPanel1.add(txt_reason);
        txt_reason.setBounds(240, 600, 380, 30);

        b_calculate.setBackground(new java.awt.Color(0, 153, 153));
        b_calculate.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        b_calculate.setForeground(new java.awt.Color(255, 255, 255));
        b_calculate.setText("Calculate");
        b_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calculateActionPerformed(evt);
            }
        });
        jPanel1.add(b_calculate);
        b_calculate.setBounds(740, 660, 140, 40);

        b_clear.setBackground(new java.awt.Color(0, 153, 153));
        b_clear.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        b_clear.setForeground(new java.awt.Color(255, 255, 255));
        b_clear.setText("Clear");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });
        jPanel1.add(b_clear);
        b_clear.setBounds(900, 660, 100, 40);

        b_save.setBackground(new java.awt.Color(0, 153, 153));
        b_save.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        b_save.setForeground(new java.awt.Color(255, 255, 255));
        b_save.setText("Save");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });
        jPanel1.add(b_save);
        b_save.setBounds(630, 660, 90, 40);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salary/management/system/dbms/images/finaldeduction.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(-450, -70, 1670, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
            int i=Integer.parseInt(txt_search.getText());
        String sql="SELECT * FROM `staff information` WHERE `id`="+i+"";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        rs.next();
           String add1=rs.getString("id");
           txt_empid.setText(add1);
           String add2=rs.getString("First_Name");
           txt_fname.setText(add2);
           String add3=rs.getString("Surname");
           txt_surname.setText(add3);
           String add4=rs.getString("Date_Of_Birth");
           txt_dob.setText(add4);
           String add5=rs.getString("Salary");
           txt_salary.setText(add5);
           String add6=rs.getString("Department");
           txt_department.setText(add6);
           String add7=rs.getString("Designation");
           txt_designation.setText(add7);
           String add8=rs.getString("Date_Hired");
           txt_hired.setText(add8);
           String add9=rs.getString("Status");
           txt_status.setText(add9);
           String add10=rs.getString("Job_Title");
           txt_title.setText(add10);
        
        
        }catch(Exception e)
        {
          // JOptionPane.showMessageDialog(null, e);
        }
        finally{
           try{ rs.close();
            pst.close();
           }catch(Exception e){
               
           }
        }
                
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
        r_percentage.setSelected(true);
        r_amount.setSelected(false);
        txt_amount.setEnabled(false);
        txt_percentage.setEditable(true);
        txt_percentage.setEnabled(true);
        txt_amount.setText("");
    }//GEN-LAST:event_r_percentageActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:
        r_amount.setSelected(true);
        r_percentage.setSelected(false);
        txt_percentage.setEnabled(false);
        txt_amount.setEditable(true);
        txt_amount.setEnabled(true);
        txt_percentage.setText("");
    }//GEN-LAST:event_r_amountActionPerformed

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
        if(r_percentage.isSelected()||r_amount.isSelected()==true){
       int x=JOptionPane.showConfirmDialog(null, "Are You sure want to save deduction?","Save",JOptionPane.YES_NO_OPTION);
     if(x==0){
         String value3=l_empid.getText();
         try{
            String creat=l_empid.getText();
            String fname=txt_fname.getText();
            String surname=txt_surname.getText();
            String damount=txt_totaldeduction.getText();
            String reason=txt_reason.getText();
            String empid=txt_empid.getText();
            String salary=txt_salary.getText();
            String sql="INSERT INTO `deductions`( `First_Name`, `Surname`, `Salary`, `Deduction_Amount`, `Deduction_Reason`, `Emp_id`, `Created_by`) VALUES ('"+fname+"','"+surname+"','"+salary+"','"+damount+"','"+reason+"','"+empid+"','"+creat+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deduction Saved");
         }catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
         finally{
             try{
                rs.close();
                pst.close();
             }catch(Exception e){
                 
             }
         }
         
         
     }}else{
            JOptionPane.showMessageDialog(null,"Please inser percentage or amount?");
        }
     
    }//GEN-LAST:event_b_saveActionPerformed

    private void txt_salaryafterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryafterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryafterActionPerformed

    private void b_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calculateActionPerformed
        // TODO add your handling code here:
       try{ int salary=Integer.parseInt(txt_salary.getText());
        if(r_percentage.isSelected()==true)
        {
            int percentage=Integer.parseInt(txt_percentage.getText());
            
            int total_percentage_deduction=salary/100*percentage;
            String x=String.valueOf(total_percentage_deduction);
           int sal=salary - total_percentage_deduction;
           txt_totaldeduction.setText(x);
           txt_salaryafter.setText(String.valueOf(sal));
        }
        if(r_amount.isSelected()==true)
        {
            int deduction =Integer.parseInt(txt_amount.getText());
            int totalamount=salary-deduction;
            String s=String.valueOf(totalamount);
            txt_totaldeduction.setText(String.valueOf(deduction));
            txt_salaryafter.setText(s);
        }
       }catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null,"Please insert correct Employee ID");
       }
        
    }//GEN-LAST:event_b_calculateActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null, "Are You sure want to Clear?","Clear",JOptionPane.YES_NO_OPTION);
     if(x==0){
        txt_empid.setText("");
        txt_fname.setText("");
        txt_surname.setText("");
        txt_dob.setText("");
        txt_department.setText("");
        txt_salary.setText("");
        txt_totaldeduction.setText("0.00");
        txt_salaryafter.setText("0.00");
        txt_search.setText("");
        txt_designation.setText("");
        txt_status.setText("");
        txt_percentage.setText("");
        txt_amount.setText("");
        //l_empid.setText("");
        txt_hired.setText("");
        txt_title.setText("");
        txt_reason.setText("");
    }                       
        
    }//GEN-LAST:event_b_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deduction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton b_calculate;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_empid;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_hired;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_reason;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_salaryafter;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_title;
    private javax.swing.JTextField txt_totaldeduction;
    // End of variables declaration//GEN-END:variables
}
