/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salary.management.system.dbms;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author TARIF
 */
public class login extends javax.swing.JFrame {
Connection conn=null;
ResultSet RS=null;
PreparedStatement PST=null;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
      //  conn=DBMS.db();
        currentDate();
    }
    public void currentDate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        date.setText((day)+"/"+(month+1)+"/"+year);
        int second=cal.get(Calendar.SECOND);
        int minute=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        time.setText("Time:"+(hour)+":"+minute+":"+second);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        txt_division = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("salary mangement");

        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 570, 150, 40);

        jButtonLogin.setBackground(new java.awt.Color(0, 102, 51));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(530, 570, 100, 40);

        txt_division.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_division.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(txt_division);
        txt_division.setBounds(280, 510, 350, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setText("Select devision:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 510, 160, 25);

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_password);
        txt_password.setBounds(280, 450, 350, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jLabel5.setText("password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 450, 110, 25);

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(txt_username);
        txt_username.setBounds(280, 390, 350, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 51));
        jLabel4.setText("username:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 390, 130, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 51));
        jLabel3.setText("please enter your username and password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 330, 770, 50);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Salary Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, -20, 680, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salary/management/system/dbms/images/login.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1266, 798));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -30, 1430, 810);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        date.setText("Date");
        jMenuBar1.add(date);

        time.setText("Time");
        jMenuBar1.add(time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1266, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
           /*int count=0;
            int id=rs.getInt(1);
            Emp.empId=id;
            String username=rs.getString("username");
            Emp.empname=username;
            count=count+1;*/
           String query="SELECT * FROM `users` WHERE username=? and password=? and division=? ";
           conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/salary management system dbms ?serverTimezone=UTC","root","");
           PST=conn.prepareStatement(query);
           PST.setString(1,txt_username.getText());
           PST.setString(2,txt_password.getText());
           PST.setString(3,String.valueOf(txt_division.getSelectedItem()));
           RS=PST.executeQuery();
           if(RS.next())
           {
               if(txt_division.getSelectedIndex()==0)
               {
                   String user=RS.getString("employee_id");
                   String username=RS.getString("username");
                   Emp.empname=username;
                   //int usernam=Integer.parseInt(user);
            //Emp.empId=usernam;
                   Menu m=new Menu();
                   m.setVisible(true);
                   this.setVisible(false);
                   Date currentDate = GregorianCalendar.getInstance().getTime();
                  DateFormat df = DateFormat.getDateInstance();
                  String dateString = df.format(currentDate);

                  Date d = new Date();
                  SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                  String timeString = sdf.format(d);

                  String value0 = timeString;
                  String values = dateString;
                   String user1=txt_username.getText();
             
                   String query1="SELECT * FROM `staff information` WHERE `Email`='"+user1+"'";
                   PST=conn.prepareStatement(query1);
                   RS=PST.executeQuery();
                   RS.next();
                   
                       String id=RS.getString("id");
                   
                   String reg = "INSERT INTO `audit`( `emp_id`, `date`, `status`) VALUES ('"+id+"','"+value0+" / "+values+"','Logged in')";
                   PST=conn.prepareStatement(reg);
                   PST.execute();
                   this.dispose();
                   
               }else if(txt_division.getSelectedIndex()==1){
                  String user=RS.getString("employee_id");
                   String username=RS.getString("username");
                   Emp.empname=username;
                   int usernam=Integer.parseInt(user);
            Emp.empId=usernam;
                   Menu m=new Menu();
                   m.setVisible(true);
                   this.setVisible(false);
                   Date currentDate = GregorianCalendar.getInstance().getTime();
                  DateFormat df = DateFormat.getDateInstance();
                  String dateString = df.format(currentDate);

                  Date d = new Date();
                  SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                  String timeString = sdf.format(d);

                  String value0 = timeString;
                  String values = dateString;
                   String user2=txt_username.getText();
             
                   
                   String query2="SELECT * FROM `staff information` WHERE `Email`='"+user2+"'";
                   PST=conn.prepareStatement(query2);
                   RS=PST.executeQuery();
                   RS.next();
                   
                       String id=RS.getString("id");
                   String reg = "INSERT INTO `audit`( `emp_id`, `date`, `status`) VALUES ('"+id+"','"+value0+" / "+values+"','Logged in')";
                   PST=conn.prepareStatement(reg);
                   PST.execute();
                   this.dispose();

               }
           }else
           {
               JOptionPane.showMessageDialog(this,"username or password incorrect");
           }
         
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        registration a=new registration();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu time;
    private javax.swing.JComboBox<String> txt_division;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
