/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salary.management.system.dbms;

//import com.itextpdf.awt.geom.Dimension;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

//import javax.swing.text.Document;

/**
 *
 * @author TARIF
 */
public class Searchemp extends javax.swing.JFrame {
     Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
    /**
     * Creates new form Searchemp
     */
    public Searchemp() {
        initComponents();
        conn=DBMS.db();
        
        
       Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_hired = new javax.swing.JTextField();
        txt_title = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_empid = new javax.swing.JTextField();
        b_slip = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Employee ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 120, 160, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 160, 160, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Surname:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 200, 160, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date Of Birth:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 240, 160, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Department:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 280, 160, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Designation:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 120, 160, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 160, 160, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Date Hired:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 200, 160, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Job Title:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 240, 160, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Basic Salary:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 280, 160, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Employee ID:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 50, 160, 50);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(280, 60, 610, 31);

        txt_fname.setEditable(false);
        txt_fname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_fname);
        txt_fname.setBounds(280, 170, 210, 30);

        txt_surname.setEditable(false);
        txt_surname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_surname);
        txt_surname.setBounds(280, 210, 210, 30);

        txt_dob.setEditable(false);
        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_dob);
        txt_dob.setBounds(280, 250, 210, 30);

        txt_department.setEditable(false);
        txt_department.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_department);
        txt_department.setBounds(280, 290, 210, 30);

        txt_designation.setEditable(false);
        txt_designation.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_designation);
        txt_designation.setBounds(690, 130, 210, 30);

        txt_status.setEditable(false);
        txt_status.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_status);
        txt_status.setBounds(690, 170, 210, 30);

        txt_hired.setEditable(false);
        txt_hired.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_hired);
        txt_hired.setBounds(690, 210, 210, 30);

        txt_title.setEditable(false);
        txt_title.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_title);
        txt_title.setBounds(690, 250, 210, 30);

        txt_salary.setEditable(false);
        txt_salary.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_salary);
        txt_salary.setBounds(690, 290, 210, 30);

        txt_empid.setEditable(false);
        txt_empid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txt_empid);
        txt_empid.setBounds(280, 130, 210, 30);

        b_slip.setBackground(new java.awt.Color(0, 153, 0));
        b_slip.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b_slip.setForeground(new java.awt.Color(255, 255, 255));
        b_slip.setText("Generate Slip");
        b_slip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_slipActionPerformed(evt);
            }
        });
        jPanel1.add(b_slip);
        b_slip.setBounds(410, 400, 200, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salary/management/system/dbms/images/searchemp.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, -110, 1030, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
         try{
            int i=Integer.parseInt(txt_search.getText());
        String sql="SELECT * FROM `staff information` WHERE `id`="+i+"";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        rs.next();
           String add1=rs.getString("id");
           txt_empid.setText(add1);
           String add2=rs.getString("First_Name");
           txt_fname.setText(add2);
           String add3=rs.getString("Surname");
           txt_surname.setText(add3);
           String add4=rs.getString("Date_Of_Birth");
           txt_dob.setText(add4);
           String add5=rs.getString("Salary");
           txt_salary.setText(add5);
           String add6=rs.getString("Department");
           txt_department.setText(add6);
           String add7=rs.getString("Designation");
           txt_designation.setText(add7);
           String add8=rs.getString("Date_Hired");
           txt_hired.setText(add8);
           String add9=rs.getString("Status");
           txt_status.setText(add9);
           String add10=rs.getString("Job_Title");
           txt_title.setText(add10);
        
        
        }catch(Exception e)
        {
           //JOptionPane.showMessageDialog(null, e);
        }
        finally{
           try{ rs.close();
            pst.close();
           }catch(Exception e){
               
           }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void b_slipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_slipActionPerformed
        // TODO add your handling code here:
        String value=txt_fname.getText();
        String value0=txt_surname.getText();
        String value1=txt_empid.getText();
        String value2=txt_designation.getText();
        String value3=txt_department.getText();
        JFileChooser dialog=new JFileChooser();
        dialog.setSelectedFile(new File(value+" "+value0+"-Salary Slip"+".pdf"));
        int dialogResult=dialog.showSaveDialog(null);
        if(dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath=dialog.getSelectedFile().getPath();
            try{
             String sql="SELECT * FROM `deductions` WHERE Emp_id='"+value1+"' ";
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             rs.next();
             String val=rs.getString("Deduction_Amount");
             String reason=rs.getString("Deduction_Reason");
             rs.close();
             pst.close();
             String sq="SELECT * FROM `allowance` WHERE Emp_id='"+value1+"' ";
             pst=conn.prepareStatement(sq);
             rs=pst.executeQuery();
             rs.next();
             int calcTotal=Integer.parseInt(txt_salary.getText());
             float x=Float.valueOf(rs.getString(8));
             int v=Integer.parseInt(val);
             float total=calcTotal+x-v;
             Document myDocument=new Document();
             PdfWriter myWriter=PdfWriter.getInstance(myDocument,new FileOutputStream(filePath) );
             myDocument.open();
             
            myDocument.add(new Paragraph("PAY SLIP",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add((new Paragraph("EMPLOYEE DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
           myDocument.add((new Paragraph("Name of Employee: " +value+" "+value0,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
           myDocument.add((new Paragraph("Designation: "+value2,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
           myDocument.add((new Paragraph("Department: "+value3,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("SALARY",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Basic Salary: "+calcTotal+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Overtime: "+rs.getString(1)+" Hours",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Medical: " +rs.getString(2)+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Bonus: "+rs.getString(3)+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Other: "+rs.getString(4)+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("DEDUCTION",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Deduction Details: "+reason,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Total Deductions : "+val+" Tk" ,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("TOTAL PAYMENT",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Total Earnings: "+rs.getString("Total_Allowance")+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Net Pay : " +total+" Tk",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           
           
           myDocument.newPage();
             
             myDocument.close();
             
             JOptionPane.showMessageDialog(null,"Report was successfully generated");
                
                
                
                
                
                
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Please Update Allowance and Deduction");
            }
       
        
        }
        
        
        
    }//GEN-LAST:event_b_slipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_slip;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_hired;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_title;
    // End of variables declaration//GEN-END:variables
}
