/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salary.management.system.dbms;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author TARIF
 */
public class UpdateSalary extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSalary
     */
    public UpdateSalary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_basicSalary = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_percentage = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        b_update = new javax.swing.JButton();
        r_amount = new javax.swing.JRadioButton();
        r_percentage = new javax.swing.JRadioButton();
        backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1201, 731));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Employee ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 180, 160, 40);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(250, 70, 720, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 230, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Surname:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 280, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Date of Birth:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 180, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Basic Salary:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 230, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Department:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(520, 280, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Update Salary by:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 400, 210, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Amount:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 470, 130, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Employee ID:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 60, 160, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Percentage:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 470, 160, 40);

        txt_firstname.setEditable(false);
        txt_firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_firstname);
        txt_firstname.setBounds(240, 240, 220, 30);

        txt_surname.setEditable(false);
        txt_surname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_surname);
        txt_surname.setBounds(240, 290, 220, 30);

        txt_dob.setEditable(false);
        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_dob);
        txt_dob.setBounds(690, 190, 220, 30);

        txt_basicSalary.setEditable(false);
        txt_basicSalary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_basicSalary);
        txt_basicSalary.setBounds(690, 240, 220, 30);

        txt_department.setEditable(false);
        txt_department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_department);
        txt_department.setBounds(690, 290, 220, 30);

        txt_percentage.setEditable(false);
        txt_percentage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_percentage);
        txt_percentage.setBounds(240, 480, 220, 30);

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_amount);
        txt_amount.setBounds(590, 480, 220, 30);

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_id);
        txt_id.setBounds(240, 190, 220, 30);

        b_update.setBackground(new java.awt.Color(0, 153, 51));
        b_update.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        b_update.setForeground(new java.awt.Color(255, 255, 255));
        b_update.setText("Update");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });
        jPanel1.add(b_update);
        b_update.setBounds(790, 540, 120, 40);

        r_amount.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        r_amount.setForeground(new java.awt.Color(255, 204, 0));
        r_amount.setText("Amount");
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });
        jPanel1.add(r_amount);
        r_amount.setBounds(460, 410, 175, 33);

        r_percentage.setBackground(new java.awt.Color(102, 102, 102));
        r_percentage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        r_percentage.setForeground(new java.awt.Color(255, 204, 0));
        r_percentage.setText("Percentage(%)");
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });
        jPanel1.add(r_percentage);
        r_percentage.setBounds(250, 410, 185, 33);

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salary/management/system/dbms/images/UpdateSalary13.png"))); // NOI18N
        jPanel1.add(backgroud);
        backgroud.setBounds(-10, -40, 1290, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            String user="root";
            String password="";
            String url="jdbc:mysql://127.0.0.1:3306/salary management system dbms?serverTimezone=UTC";
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement statment = conn.createStatement();  
            String id=txt_search.getText();
            int i=Integer.parseInt(id);
            String sql="SELECT * FROM `staff information` WHERE `id`="+i+"";
            ResultSet rs;
            rs=statment.executeQuery(sql);
            rs.next();
            String add1=rs.getString("id");
            txt_id.setText(add1);
            String add2=rs.getString("First_Name");
            txt_firstname.setText(add2);
            String add3=rs.getString("Surname");
            txt_surname.setText(add3);
            String add4=rs.getString("Date_Of_Birth");
            txt_dob.setText(add4);
            String add5=rs.getString("Department");
            txt_department.setText(add5);
            String add6=rs.getString("Salary");
            txt_basicSalary.setText(add6);
            
            
            
        }catch(Exception e)
        {
         // JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        
        int salary=Integer.parseInt(txt_basicSalary.getText());
        
        if(r_percentage.isSelected()==true){
        int getPercentage=Integer.parseInt(txt_percentage.getText());
        int calPercentage=((salary/100)*getPercentage)+salary;
        String xP=String.valueOf(calPercentage);
        txt_basicSalary.setText(xP);
        }else if(r_amount.isSelected()==true){
        int getAmt=Integer.parseInt(txt_amount.getText());
        int calAmount=salary+getAmt;
        String xA=String.valueOf(calAmount);
        txt_basicSalary.setText(xA);}
        
        
        
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            String user="root";
            String password="";
            String url="jdbc:mysql://127.0.0.1:3306/salary management system dbms?serverTimezone=UTC";
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement statment = conn.createStatement();  
            int i=Integer.parseInt(txt_id.getText());
            String value2=txt_basicSalary.getText();
            String sql="UPDATE `staff information` SET `Salary`='"+value2+"' WHERE `id`="+i+" ";
            statment.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Record Updated");
            statment.close();
            conn.close();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_b_updateActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:
        r_amount.setSelected(true);
        r_percentage.setSelected(false);
        txt_percentage.setEnabled(false);
        txt_amount.setEditable(true);
        txt_amount.setEnabled(true);
        txt_percentage.setText("");
        
    }//GEN-LAST:event_r_amountActionPerformed

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
        r_percentage.setSelected(true);
        r_amount.setSelected(false);
        txt_amount.setEnabled(false);
        txt_percentage.setEditable(true);
        txt_percentage.setEnabled(true);
        txt_amount.setText("");
        
        
    }//GEN-LAST:event_r_percentageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_update;
    private javax.swing.JLabel backgroud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_basicSalary;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
